services:
  db:
    image: postgres:15
    container_name: pisofire-db
    ports:
      - "5432:5432" # Expõe para o npx conseguir ver do lado de fora
    environment:
      - POSTGRES_USER=pisofire
      - POSTGRES_PASSWORD=pisofire
      - POSTGRES_DB=pisofire123
    volumes:
      - ./postgres-data:/var/lib/postgresql/data