apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pisofire
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres.yaml
  - redis.yaml
  - medusa.yaml
  - bootstrap-job.yaml
  - storefront.yaml
