apiVersion: v1
kind: Secret
metadata:
  name: pisofire-secrets
  namespace: pisofire
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
  JWT_SECRET: supersecret
  COOKIE_SECRET: supersecret
  REVALIDATE_SECRET: supersecret
