apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backups
  namespace: pisofire
spec:
  storageClassName: longhorn-rs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
